# Generated by Django 4.2.3 on 2024-01-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('psw1', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='items',
            name='price',
            field=models.IntegerField(max_length=200),
        ),
    ]
