# Generated by Django 5.1 on 2024-10-10 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0006_documenttitle_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='docs/')),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='document',
        ),
        migrations.CreateModel(
            name='StudentDet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('grade', models.CharField(max_length=10)),
                ('doc_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='front.doctitle')),
            ],
        ),
        migrations.DeleteModel(
            name='DocumentTitle',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
