# Generated by Django 5.1 on 2024-10-10 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0007_doctitle_remove_student_document_studentdet_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentdet',
            unique_together={('doc_title', 'name')},
        ),
    ]
